version: "3.8"

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: infra_ready_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./backend/utils:/docker-entrypoint-initdb.d:ro

  app:
    build: .
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      PGUSER: postgres
      PGPASSWORD: password
      PGDATABASE: infra_ready_db
      PGHOST: db
      PGPORT: 5432
    command: node index.js

volumes:
  pgdata:
