- uses: actions/checkout@v2

- name: Setup Node.js
  uses: actions/setup-node@v2
  with:
    node-version: "18"

- name: Install dependencies
  run: npm install
  working-directory: ./backend

- name: Wait for Postgres to be ready
  run: |
    until pg_isready -h localhost -p 5432 -U postgres; do
      echo "Waiting for Postgres to be ready..."
      sleep 2
    done

- name: List DB init files (for debug)
  run: ls -l ./backend/db/

- name: Run DB initialization script
  run: |
    PGPASSWORD=password psql -h localhost -U postgres -d testdb -f ./backend/db/init.sql -a -v
  env:
    PGPASSWORD: password

- name: Show current directory and files
  run: |
    pwd
    ls -la

- name: Run tests
  run: npm run test
  working-directory: ./backend
